export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_PAGE_REQUEST = 'FETCH_PRODUCT_PAGE_REQUEST';
export const FETCH_PRODUCT_PAGE_SUCCESS = 'FETCH_PRODUCT_PAGE_SUCCESS';
