export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_PAGE_REQUEST = 'FETCH_PRODUCT_PAGE_REQUEST';
export const FETCH_PRODUCT_PAGE_SUCCESS = 'FETCH_PRODUCT_PAGE_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';